<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527185749 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE demande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message VARCHAR(1000) NOT NULL, date_creation DATE NOT NULL, statut VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, user_id_id INT NOT NULL, admin_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2694D7A59D86650F ON demande (user_id_id)');
        $this->addSql('CREATE INDEX IDX_2694D7A5DF6E65AD ON demande (admin_id_id)');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A59D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5DF6E65AD FOREIGN KEY (admin_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE demande DROP CONSTRAINT FK_2694D7A59D86650F');
        $this->addSql('ALTER TABLE demande DROP CONSTRAINT FK_2694D7A5DF6E65AD');
        $this->addSql('DROP TABLE demande');
    }
}
