<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260529212516 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE controle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note DOUBLE PRECISION DEFAULT NULL, type VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, enseignement_id_id INT NOT NULL, etudiant_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E39396ECB02C210 ON controle (enseignement_id_id)');
        $this->addSql('CREATE INDEX IDX_E39396E7EB24B ON controle (etudiant_id_id)');
        $this->addSql('CREATE TABLE enseignement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, date_debut DATE NOT NULL, niveau_scolaire_info_classe VARCHAR(255) NOT NULL, niveau_scolaire_info_annee INT NOT NULL, niveau_scolaire_info_niveau VARCHAR(255) NOT NULL, niveau_scolaire_info_fillier VARCHAR(255) NOT NULL, professeur_id_id INT NOT NULL, matiere_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD310CCEE1AF529 ON enseignement (professeur_id_id)');
        $this->addSql('CREATE INDEX IDX_BD310CCF3E43022 ON enseignement (matiere_id_id)');
        $this->addSql('CREATE TABLE matiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, filiere VARCHAR(255) NOT NULL, niveau VARCHAR(255) NOT NULL, semestre INT NOT NULL, nom_matiere VARCHAR(255) NOT NULL, coefficient DOUBLE PRECISION NOT NULL, types_controle JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE reclamation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(255) NOT NULL, controle_id_id INT NOT NULL, admin_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CE606404EC0E5C37 ON reclamation (controle_id_id)');
        $this->addSql('CREATE INDEX IDX_CE606404DF6E65AD ON reclamation (admin_id_id)');
        $this->addSql('ALTER TABLE controle ADD CONSTRAINT FK_E39396ECB02C210 FOREIGN KEY (enseignement_id_id) REFERENCES enseignement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE controle ADD CONSTRAINT FK_E39396E7EB24B FOREIGN KEY (etudiant_id_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enseignement ADD CONSTRAINT FK_BD310CCEE1AF529 FOREIGN KEY (professeur_id_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enseignement ADD CONSTRAINT FK_BD310CCF3E43022 FOREIGN KEY (matiere_id_id) REFERENCES matiere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE606404EC0E5C37 FOREIGN KEY (controle_id_id) REFERENCES controle (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE reclamation ADD CONSTRAINT FK_CE606404DF6E65AD FOREIGN KEY (admin_id_id) REFERENCES app_user (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE controle DROP CONSTRAINT FK_E39396ECB02C210');
        $this->addSql('ALTER TABLE controle DROP CONSTRAINT FK_E39396E7EB24B');
        $this->addSql('ALTER TABLE enseignement DROP CONSTRAINT FK_BD310CCEE1AF529');
        $this->addSql('ALTER TABLE enseignement DROP CONSTRAINT FK_BD310CCF3E43022');
        $this->addSql('ALTER TABLE reclamation DROP CONSTRAINT FK_CE606404EC0E5C37');
        $this->addSql('ALTER TABLE reclamation DROP CONSTRAINT FK_CE606404DF6E65AD');
        $this->addSql('DROP TABLE controle');
        $this->addSql('DROP TABLE enseignement');
        $this->addSql('DROP TABLE matiere');
        $this->addSql('DROP TABLE reclamation');
    }
}
