<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260528130812 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE commentaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu VARCHAR(255) NOT NULL, date_creation DATE NOT NULL, post_id_id INT NOT NULL, auteur_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67F068BCE85F12B8 ON commentaire (post_id_id)');
        $this->addSql('CREATE INDEX IDX_67F068BC75F8742E ON commentaire (auteur_id_id)');
        $this->addSql('CREATE TABLE groupe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, date_creation DATE NOT NULL, moderateur_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4B98C21272F518E ON groupe (moderateur_id_id)');
        $this->addSql('CREATE TABLE post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu VARCHAR(1000) NOT NULL, date_creation DATE NOT NULL, group_id_id INT NOT NULL, auteur_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D2F68B530 ON post (group_id_id)');
        $this->addSql('CREATE INDEX IDX_5A8A6C8D75F8742E ON post (auteur_id_id)');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BCE85F12B8 FOREIGN KEY (post_id_id) REFERENCES post (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commentaire ADD CONSTRAINT FK_67F068BC75F8742E FOREIGN KEY (auteur_id_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE groupe ADD CONSTRAINT FK_4B98C21272F518E FOREIGN KEY (moderateur_id_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D2F68B530 FOREIGN KEY (group_id_id) REFERENCES groupe (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE post ADD CONSTRAINT FK_5A8A6C8D75F8742E FOREIGN KEY (auteur_id_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BCE85F12B8');
        $this->addSql('ALTER TABLE commentaire DROP CONSTRAINT FK_67F068BC75F8742E');
        $this->addSql('ALTER TABLE groupe DROP CONSTRAINT FK_4B98C21272F518E');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8D2F68B530');
        $this->addSql('ALTER TABLE post DROP CONSTRAINT FK_5A8A6C8D75F8742E');
        $this->addSql('DROP TABLE commentaire');
        $this->addSql('DROP TABLE groupe');
        $this->addSql('DROP TABLE post');
    }
}
