<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527201524 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cin INT NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, mot_de_pass VARCHAR(255) NOT NULL, discr VARCHAR(255) NOT NULL, titre VARCHAR(255) DEFAULT NULL, niveau_scolaire_classe VARCHAR(255) DEFAULT NULL, niveau_scolaire_annee INT DEFAULT NULL, niveau_scolaire_niveau VARCHAR(255) DEFAULT NULL, niveau_scolaire_fillier VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE "user" CASCADE');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A59D86650F FOREIGN KEY (user_id_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT FK_2694D7A5DF6E65AD FOREIGN KEY (admin_id_id) REFERENCES app_user (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cin INT NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, mot_de_pass VARCHAR(255) NOT NULL, discr VARCHAR(255) NOT NULL, titre VARCHAR(255) DEFAULT NULL, niveau_scolaire_classe VARCHAR(255) DEFAULT NULL, niveau_scolaire_annee INT DEFAULT NULL, niveau_scolaire_niveau VARCHAR(255) DEFAULT NULL, niveau_scolaire_fillier VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('ALTER TABLE demande DROP CONSTRAINT FK_2694D7A59D86650F');
        $this->addSql('ALTER TABLE demande DROP CONSTRAINT FK_2694D7A5DF6E65AD');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT fk_2694d7a59d86650f FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE demande ADD CONSTRAINT fk_2694d7a5df6e65ad FOREIGN KEY (admin_id_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
