<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260528131140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE membre_groupe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_adhesion DATE NOT NULL, user_id_id INT NOT NULL, groupe_d_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9EB019989D86650F ON membre_groupe (user_id_id)');
        $this->addSql('CREATE INDEX IDX_9EB01998A4E8DCDD ON membre_groupe (groupe_d_id)');
        $this->addSql('ALTER TABLE membre_groupe ADD CONSTRAINT FK_9EB019989D86650F FOREIGN KEY (user_id_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE membre_groupe ADD CONSTRAINT FK_9EB01998A4E8DCDD FOREIGN KEY (groupe_d_id) REFERENCES groupe (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE membre_groupe DROP CONSTRAINT FK_9EB019989D86650F');
        $this->addSql('ALTER TABLE membre_groupe DROP CONSTRAINT FK_9EB01998A4E8DCDD');
        $this->addSql('DROP TABLE membre_groupe');
    }
}
