<?php
namespace App\Enum;

enum StatutReclamationEnum: string
{
    case EN_ATTENTE = 'EN_ATTENTE';
    case ACCEPTEE_PAR_LE_PROFESSEUR = 'ACCEPTEE_PAR_LE_PROFESSEUR';
    case ACCEPTEE_PAR_ADMINISTRATEUR = 'ACCEPTEE_PAR_ADMINISTRATEUR';
    case REFUSEE_PAR_LE_PROFESSEUR = 'REFUSEE_PAR_LE_PROFESSEUR';
    case REFUSEE_PAR_ADMINISTRATEUR = 'REFUSEE_PAR_ADMINISTRATEUR';
}
